services:
  app:
    build: .
    container_name: book_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - backend-network

  db:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root123
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U root -d postgres
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge